FROM python:3.8

WORKDIR /app

COPY requirements.txt ./

RUN pip install --upgrade pip setuptools wheel && \
    pip install --no-cache-dir numpy==1.24.4 && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "monitor.py"]


