apiVersion: v1
kind: Service
metadata:
  name: burnout-service
spec:
  type: LoadBalancer
  selector:
    app: burnout
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
