name: CI - Run Unit Tests on PR/Push

on:
  push:
    branches: [ main, dev, feature/* ]
  pull_request:
    branches: [ main, dev ]

jobs:
  run-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use system Python
        run: |
          echo "Using system Python:"
          python3 --version
          which python3

      - name: Set up venv and install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: |
          source venv/bin/activate
          pytest tests/test_pipeline.py
