name: CI - Build and Push Docker Image (Manual or on Push)

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted  # or change to ubuntu-latest if not using your own VM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current directory
        run: pwd

      - name: List all files (debugging)
        run: ls -R

      - name: Check Docker installation
        run: docker version

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image with no cache and full logs
        run: docker build --no-cache --progress=plain -t vmontanha/burnout-api:v3 .

      - name: List Docker images (sanity check)
        run: docker images

      - name: Push image to Docker Hub
        run: docker push vmontanha/burnout-api:v3

