name: CM + CT - Daily Drift Check, Retrain and Docker Push

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  monitor-and-retrain:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up venv and install compatible dependencies
        run: |
          python3 -m venv venv
          venv/bin/pip install --upgrade pip setuptools wheel
          venv/bin/pip install numpy==1.19.5 pandas==1.1.5 scikit-learn==0.24.2 joblib==1.1.1 matplotlib==3.3.4

      - name: Run monitoring script (inside venv)
        run: |
          venv/bin/python monitor.py

      - name: Check if retrained model exists and prepare Docker tag
        run: |
          FILE=$(ls burnout_model_v*.pkl 2>/dev/null | tail -n 1)
          if [[ -z "$FILE" ]]; then
            echo "No retrained model found, exiting."
            exit 0
          fi
          TAG=$(basename "$FILE" .pkl | sed 's/[^a-zA-Z0-9_.-]/-/g')
          echo "MODEL_FILE=$FILE" >> $GITHUB_ENV
          echo "MODEL_TAG=$TAG" >> $GITHUB_ENV

      - name: Build and Push Docker Image (if model retrained)
        if: env.MODEL_TAG != ''
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          cp "$MODEL_FILE" burnout_model.pkl
          docker build -t $DOCKER_HUB_USERNAME/burnout-api:$MODEL_TAG .
          echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker push $DOCKER_HUB_USERNAME/burnout-api:$MODEL_TAG



