name: CM + CT - Daily Drift Check, Retrain and Docker Push

on:
  schedule:
    - cron: "0 2 * * *"  # Every day at 2:00 AM UTC
  workflow_dispatch:

jobs:
  monitor-and-retrain:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies system-wide
        run: |
          python3 -m pip install --upgrade pip
          pip install --user numpy pandas scikit-learn joblib matplotlib pytest

          # Attempt nannyml install only if Python >= 3.9
          PY_VER=$(python3 -c 'import sys; print(sys.version_info.minor)')
          if [ "$PY_VER" -ge 9 ]; then
            pip install --user nannyml
          else
            echo "Skipping nannyml install — requires Python >= 3.9"
          fi

      - name: Run monitoring script
        run: |
          python3 monitor.py

      - name: Check if retrained model exists and prepare Docker tag
        run: |
          FILE=$(ls burnout_model_v*.pkl 2>/dev/null | tail -n 1)
          if [[ -z "$FILE" ]]; then
            echo "No retrained model found, exiting."
            exit 0
          fi
          TAG=$(basename "$FILE" .pkl | sed 's/[^a-zA-Z0-9_.-]/-/g')
          echo "MODEL_FILE=$FILE" >> $GITHUB_ENV
          echo "MODEL_TAG=$TAG" >> $GITHUB_ENV

      - name: Build and Push Docker Image (if model retrained)
        if: env.MODEL_TAG != ''
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          cp "$MODEL_FILE" burnout_model.pkl
          docker build -t $DOCKER_HUB_USERNAME/burnout-api:$MODEL_TAG .
          echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker push $DOCKER_HUB_USERNAME/burnout-api:$MODEL_TAG


