name: CM + CT - Daily Drift Check, Retrain and Docker Push

on:
  schedule:
    - cron: "0 2 * * *"  # Every day at 2:00 AM UTC
  workflow_dispatch:

jobs:
  monitor-and-retrain:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image for Monitoring
        run: |
          docker build -t burnout-monitor:latest .

      - name: Run Monitoring Script
        run: |
          docker run --rm -v ${{ github.workspace }}:/opt/app burnout-monitor:latest python monitor.py

      - name: Set Model Tag from Retrain Output
        run: |
          TAG=$(ls burnout_model_v*.pkl 2>/dev/null | tail -n 1 | sed 's/\.pkl//')
          echo "MODEL_TAG=$TAG" >> $GITHUB_ENV

      - name: Build and Push Docker Image (if model retrained)
        if: env.MODEL_TAG != ''
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          cp $MODEL_TAG.pkl burnout_model.pkl
          docker build -t $DOCKER_HUB_USERNAME/burnout-api:$MODEL_TAG .
          echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker push $DOCKER_HUB_USERNAME/burnout-api:$MODEL_TAG

