name: CM + CT - Daily Drift Check, Retrain and Docker Push

on:
  schedule:
    - cron: "0 2 * * *"  # Every day at 2:00 AM UTC
  workflow_dispatch:

jobs:
  monitor-and-retrain:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up venv and install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install numpy  # Let pip choose compatible version

      - name: Run monitoring script
        run: |
          source venv/bin/activate
          python monitor.py

      - name: Check if retrained model exists and prepare safe Docker tag
        run: |
          TAG=$(ls burnout_model_v*.pkl 2>/dev/null | tail -n 1 | sed 's/\.pkl//' | sed 's/[^a-zA-Z0-9_.-]//g')
          echo "MODEL_TAG=$TAG" >> $GITHUB_ENV

      - name: Build and Push Docker Image (if model retrained)
        if: env.MODEL_TAG != ''
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          cp burnout_model_${{ env.MODEL_TAG }}.pkl burnout_model.pkl
          docker build -t $DOCKER_HUB_USERNAME/burnout-api:${{ env.MODEL_TAG }} .
          echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker push $DOCKER_HUB_USERNAME/burnout-api:${{ env.MODEL_TAG }}
