name: CM + CT - Daily Drift Check, Retrain and Docker Push

on:
  schedule:
    - cron: "0 2 * * *"  # Every day at 2:00 AM UTC
  workflow_dispatch:

jobs:
  monitor-and-retrain:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python venv and install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          
          PYTHON_VERSION=$(python -c "import sys; print(sys.version_info.minor)")
          
          if [ "$PYTHON_VERSION" -ge 8 ]; then
            echo "Installing all dependencies including nannyml"
            pip install -r requirements.txt
          else
            echo "Installing without nannyml due to old Python version"
            grep -v 'nannyml' requirements.txt > temp-reqs.txt
            pip install -r temp-reqs.txt
          fi

      - name: Run monitoring script
        run: |
          source venv/bin/activate
          python monitor.py

      - name: Check if retrained model exists and prepare Docker tag
        run: |
          FILE=$(ls burnout_model_v*.pkl 2>/dev/null | tail -n 1)
          if [[ -z "$FILE" ]]; then
            echo "No retrained model found, exiting."
            exit 0
          fi
          TAG=$(basename "$FILE" .pkl | sed 's/[^a-zA-Z0-9_.-]/-/g')
          echo "MODEL_FILE=$FILE" >> $GITHUB_ENV
          echo "MODEL_TAG=$TAG" >> $GITHUB_ENV

      - name: Build and Push Docker Image (if model retrained)
        if: env.MODEL_TAG != ''
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          cp "$MODEL_FILE" burnout_model.pkl
          docker build -t $DOCKER_HUB_USERNAME/burnout-api:$MODEL_TAG .
          echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker push $DOCKER_HUB_USERNAME/burnout-api:$MODEL_TAG



