name: CM - Drift Check Only (Every 30min)


on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes
  workflow_dispatch:

jobs:
  monitor_and_retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitor.py
        run: |
          python monitor.py

      - name: Commit and push new model if retrained
        run: |
          if git status | grep -q "burnout_model.pkl"; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add burnout_model.pkl burnout_model_v*.pkl
            git commit -m "chore: retrained model pushed by cron job"
            git push origin dev
          else
            echo "No retraining needed. No files changed."
