name: CM + CT - Daily Drift Check, Retrain and Docker Push

on:
  schedule:
    - cron: "0 2 * * *"  # Daily at 2:00 AM UTC
  workflow_dispatch:

jobs:
  monitor-and-retrain:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python venv and install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install numpy==1.23.5 pandas==1.3.5 scikit-learn==0.24.2 joblib==1.1.1 matplotlib==3.5.3 pytest

      - name: Run monitoring script (inside virtual environment)
        run: |
          source venv/bin/activate
          python monitor.py

      - name: Check if retrained model exists and prepare Docker tag
        run: |
          TAG=$(ls burnout_model_v*.pkl 2>/dev/null | tail -n 1 | sed 's/\.pkl//')
          echo "MODEL_TAG=$TAG" >> $GITHUB_ENV

      - name: Build and Push Docker Image (if model retrained)
        if: env.MODEL_TAG != ''
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          cp "$MODEL_TAG.pkl" burnout_model.pkl
          docker build -t $DOCKER_HUB_USERNAME/burnout-api:$MODEL_TAG .
          echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker push $DOCKER_HUB_USERNAME/burnout-api:$MODEL_TAG




