name: CT - Monitor and Retrain Model

on:
  schedule:
    - cron: "0 * * * *"  # Every hour
  workflow_dispatch:

jobs:
  monitor-and-retrain:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up venv and install dependencies
        run: |
          python3 -m venv venv
          venv/bin/pip install --upgrade pip
          venv/bin/pip install -r requirements.txt

      - name: Run monitoring script
        run: venv/bin/python monitor.py

      - name: Check if retrained model exists
        run: |
          echo "MODEL_TAG=$(ls burnout_model_v*.pkl 2>/dev/null | tail -n 1 | sed 's/\.pkl//')" >> $GITHUB_ENV

      - name: Build and Push New Docker Image
        if: env.MODEL_TAG != ''
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          cp $MODEL_TAG.pkl burnout_model.pkl
          docker build -t $DOCKER_HUB_USERNAME/burnout-api:$MODEL_TAG .
          echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker push $DOCKER_HUB_USERNAME/burnout-api:$MODEL_TAG


